### PR TITLE
feat(icon): add time-delay icon

### PR DESCRIPTION
**Pull request by lt83870**
# Description

Add time-delay icon to Icons folder. Icon provided by @james-hayden-ellis
https://deploy-preview-83--legal-and-general-canopy.netlify.app/?path=/story/components-icon--standard

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [x] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts
- [ ] I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)

### CODE REVIEW

**Comment by thatguynamedandy** [comment]
I paired with @lt83870 on this one, but I need to pull it down just to verify the commit.

It does also look like something odd happened in the latest version of `svg-to-ts`.

**Comment by thatguynamedandy** [comment]
I've done a bit of checking and I think when pulled in the latest version of [svg-to-ts](https://github.com/kreuzerk/svg-to-ts) we may have inadvertently exposed a breaking change. 

Each icon set now exports.. 
`export type IconNameSubset<T extends Readonly<Icon[]>> = T[number]['name']; `

However the name is the same across both the Icon and BrandIcon set, hence the error in the build.

Possible solutions.
- Make a temporary modification to the generated files
- Raise an issue or ideally a PR into svg-to-ts
- Revert the version to get this icon in

**Comment by elenagarrone** [comment]
> I've done a bit of checking and I think when pulled in the latest version of [svg-to-ts](https://github.com/kreuzerk/svg-to-ts) we may have inadvertently exposed a breaking change.
> 
> Each icon set now exports..
> `export type IconNameSubset<T extends Readonly<Icon[]>> = T[number]['name']; `
> 
> However the name is the same across both the Icon and BrandIcon set, hence the error in the build.
> 
> Possible solutions.
> 
> * Make a temporary modification to the generated files
> * Raise an issue or ideally a PR into svg-to-ts
> * Revert the version to get this icon in

I'd say revert the version and then we can look into this a bit better.

**Comment by thatguynamedandy** [comment]
I've reverted and pinned the working version of svg-to-ts. I've also raised an [issue](https://github.com/kreuzerk/svg-to-ts/issues/91) into svg-to-ts just to see if they think it's a legitimate bug or something we should workaround.

**Review by elenagarrone — APPROVED** [review]

**Review by thatguynamedandy — APPROVED** [review]

**Pull request merged**
