### PR TITLE
Add a new icon - transfers

### PR DESCRIPTION
**Pull request by st3fun1**
# Description

A new icon has been added to the icons catalog.

## Requirements

Screenshot:

image

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have added the documentation
- [ ] I have added any new public feature modules to public-api.ts

### CODE REVIEW

**Comment by elenagarrone** [comment]
Looks like the other icons where only optimised and the attributes are ordered so that's good 👍  I'll deploy it now :)

**Comment by elenagarrone** [comment]
> Looks like the other icons where only optimised and the attributes are ordered so that's good 👍 I'll deploy it now :)

Just looking at the test environment and your branch it looks like actually some of the changes are breaking the brand icons. Have you done and `npm i` recently?

**Comment by elenagarrone** [comment]
Tested and it looks good 👍

**Review by elenagarrone — APPROVED** [review]
Thank you!

**Review by Xinchro — APPROVED** [review]

**Pull request merged**
