### PR TITLE
fix(hero): ensure content is clickable

### LINKED ISSUE #158: Breadcrumb items in hero header are not clickable
This issue is raised from the discussion raise by @p-m-p 
https://github.com/Legal-and-General/canopy/discussions/154

### PR DESCRIPTION
**Pull request by aaronBery**
# Description

Allows breadcrumb items in hero header to be clickable.
Allows links in hero notifications panel to be clickable

Fixes #158

## Requirements

Browse to the test app and ensure the breadcrumb items in the hero header can be clicked/selected
Browse to the hero product details page and ensure the contact us link in the notifications panel can be clicked

Storybook link: https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/test-page--standard
https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/components-hero--product-details
Screenshot:
Screenshot 2021-01-14 at 16 52 17

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts
- [ ] I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)

### CODE REVIEW

**Comment by thatguynamedandy** [comment]
Thanks for picking this up @aaronBery, while you are in there I think there may be a similar thing going on in this example..

https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/components-hero--product-data

The 'contact us' link isn't currently clickable.

**Review by owensgit — APPROVED** [review]
Thanks for picking this up @aaronBery  👍

**Comment by aaronBery** [comment]
> Thanks for picking this up @aaronBery, while you are in there I think there may be a similar thing going on in this example..
> 
> https://deploy-preview-159--legal-and-general-canopy.netlify.app/?path=/story/components-hero--product-data
> 
> The 'contact us' link isn't currently clickable.

sure, will do

**Comment by aaronBery** [comment]
@thatguynamedandy  @owensgit  I've fixed the contact us link in the notifications panel too. Can I get a review of the addition :-)

**Review by owensgit — APPROVED** [review]
Great, thanks for adding the contact us link as well 👍

**Review by owensgit — APPROVED** [review]

**Review by thatguynamedandy — APPROVED** [review]
Thanks for fixing this @aaronBery.

**Pull request merged**
