### PR TITLE
Removed solid-secondary button

### LINKED ISSUE #450: Remove `solid-secondary` button as it's deprecated
The `solid-secondary` button needs removing as the designers said we should only be using the blue one.

We could avoid a breaking change by setting it to be blue initially as the `solid-primary`.

### PR DESCRIPTION
**Pull request by Patil2099**
Fixes #450

### CODE REVIEW

**Comment by elenagarrone** [comment]
Thank you very much @Patil2099 for picking this up 👏  it all looks good, I've only updated the base branch to be `next` since this is going to be a breaking change and we usually group them in `next` before releasing them all together.

Could you please update the commit message to follow [conventional commits](https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#conventional-commits) standards?

For example in this case I would write something like:
```
feat(buttons): remove solid-secondary button

fix: #450
```

Thanks for contributing!

**Comment by andy-polhill** [comment]
> Thank you very much @Patil2099 for picking this up 👏 it all looks good, I've only updated the base branch to be `next` since this is going to be a breaking change and we usually group them in `next` before releasing them all together.
> 
> Could you please update the commit message to follow [conventional commits](https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#conventional-commits) standards?
> 
> For example in this case I would write something like:
> 
> ```
> feat(buttons): remove solid-secondary button
> 
> fix: #450
> ```
> 
> Thanks for contributing!

This is ace thanks @Patil2099. Just to add, you can use `npm run commit`, this will help to build the commit message for you by asking prompts in the command line, from there you can actually mention that it's a breaking change when it asks.

**Comment by andy-polhill** [comment]
linking to #315 as we are putting this into the `next` branch

**Comment by elenagarrone** [comment]
> For example in this case I would write something like:
> 
> ```
> feat(buttons): remove solid-secondary button
> 
> fix: #450
> ```

Apologies this should actually be:
```
feat(buttons): remove solid-secondary button

BREAKING CHANGE: remove the `solid-secondary` button. Use the `solid-primary` or any other button instead.

fix: #450
```

**Comment by owensgit** [comment]
Hi @Patil2099 just wondering if you've had a chance to look at the comments above? Please feel free to reach out to one of us if you'd like to chat in more detail, we're happy to help.

**Comment by owensgit** [comment]
@Patil2099  - Apologies, I tried to edit the commit message for you, but for some reason this closed the PR and doesn't show the edited commit. I've opened a new PR now because I can't seem to reopen this one: https://github.com/Legal-and-General/canopy/pull/456

Many thanks again for your contribution, it's greatly appreciated! Don't hesitate to contribute again if you'd like or get in touch if you need any support with using Canopy.

**Pull request closed without merging**
