### PR TITLE
Add responsible investing icon

### PR DESCRIPTION
**Pull request by st3fun1**
# Description

This PR adds a new brand icon to the brand icons catalog.

## Requirements
Screenshot: 
image

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)

### CODE REVIEW

**Comment by st3fun1** [comment]
> Hey @st3fun1, Could you ask the designer to recreate the icon with the correct layers so that branding can be applied please?
> 
> Screenshot 2023-11-16 at 09 03 42

@elenagarrone I've updated the icon

**Comment by st3fun1** [comment]
> Hey @st3fun1, Could you ask the designer to recreate the icon with the correct layers so that branding can be applied please?
> 
> Screenshot 2023-11-16 at 09 03 42

image

**Review by elenagarrone — APPROVED** [review]
Looking good now, thank you 🙏 

Screenshot 2023-11-16 at 11 01 23

**Review by NemirStephan — APPROVED** [review]
There are a couple of GitHub codeQL warnings. Nothing major, but might as well fix them

**Comment by elenagarrone** [comment]
> There are a couple of GitHub codeQL warnings. Nothing major, but might as well fix them

I don't think they were introduced with this PR so I would ignore them for the time being.

**Pull request merged**
