### PR TITLE
feat(icon): add from-other-benefit icon

### PR DESCRIPTION
**Pull request by AlexandruHoisan**
Add from-other-benefit icon to Icons
MAF-9932

# Description

Add the new "from-other-benefit" icon to the already existing icons.

## Requirements

Please briefly outline any requirements for the work which may aid the testing and review process.

Storybook link: (once netlify has deployed link provide a link to the component)
Design link: [(design)](https://legalandgeneral.invisionapp.com/console/share/T92YH584X4/675316029)
Screenshot: 
Screenshot 2021-12-21 at 13 15 33

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts

### CODE REVIEW

**Review by paul-request — APPROVED** [review]

**Review by aaronBery — DISMISSED** [review]

**Review by elenagarrone — CHANGES_REQUESTED** [review]
@AlexandruHoisan the name of the icon seem a bit too specific - can we make it more generic?

**Comment by AlexandruHoisan** [comment]
> 

@elenagarrone I named it like this as Michelle mentioned it might be worth keeping the icon's name so other designers can find it too. I am ok either way, but this is how the designers will look for this particular icon. :)

**Comment by AlexandruHoisan** [comment]
> @AlexandruHoisan the name of the icon seem a bit too specific - can we make it more generic?

Changed the name to `arrow-right-circle` to be more generic. :)

**Review by elenagarrone — APPROVED** [review]
Thanks for making the change 👍

**Review by aaronBery — APPROVED** [review]
thanks, that name is a lot better on reflection

**Pull request merged**
