### PR TITLE
feat(hero): implement new hero background colour & remove gradient

### LINKED ISSUE #180: Remove Gradient from Hero component
The Hero component gradient needs to be flattened to a solid colour. The gradient is longer needed for any components and can be completely removed.

The colour may exist already, or may need adding to the palette.

Colour name: `--color-super-blue-dark` 

Colour hex: `#175EA1`

### PR DESCRIPTION
**Pull request by owensgit**
# Description

Removes the gradient background from the Hero component and from the CSS vars, as it will no longer be used.

**BREAKING CHANGE** - Removes the following CSS variables: `--gradient-super-blue`, `--hero-bg-image`

Fixes #180

## Requirements

Storybook link: (once netlify has deployed link provide a link to the component)

Screenshot: 
Screenshot 2021-01-28 at 09 27 39

# Checklist:

- [x] The commit messages follow the [convention for this project](./blob/master/docs/CONTRIBUTING.md#conventional-commits)
- [ ] I have provided an adequate amount of test coverage
- [ ] I have added the functionality to the [test app](./blob/master/docs/CONTRIBUTING.md#build-test-application)
- [ ] I have provided a story in storybook to document the changes
- [ ] I have provided documentation in the notes section of the story
- [ ] I have added any new public feature modules to public-api.ts
- [ ] I have [linked the new component](<(https://github.com/Legal-and-General/canopy/blob/master/docs/CONTRIBUTING.md#invision-dsm)>) to adobe DSM (if appropriate)

### CODE REVIEW

**Comment by alexcanning** [comment]
Looks good to me!

**Review by thatguynamedandy — APPROVED** [review]

**Comment by thatguynamedandy** [comment]
Thanks for picking this up @owensgit, we so far haven't shied away too much from breaking changes, but there is the option here to leave the css vars and deprecate them in some way. Then do a bulk breaking change when there is enough deprecated code. For now though, nobody has really complained about it.

**Review by elenagarrone — APPROVED** [review]

**Comment by owensgit** [comment]
> Thanks for picking this up @owensgit, we so far haven't shied away too much from breaking changes, but there is the option here to leave the css vars and deprecate them in some way. Then do a bulk breaking change when there is enough deprecated code. For now though, nobody has really complained about it.

Sounds great. There isn't a huge rush with this PR, so I've started a chat in Slack to talk about managing breaking changes. I'l see what comes of that, and I may adjust this PR as a result 👍

**Comment by owensgit** [comment]
Closing this down, as I somehow made a mess of the commit history. Simpler now to start a new one with the CSS vars deprecated rather than removed.

**Pull request closed without merging**
